#!/bin/bash
########
#
#
#  NAME: CTcopy
#  PURPOSE: Used to copy all CTs from 1 Blueprint in an
#                Apstra 5.x server to 1 Blueprint in another Apstra 5.x server
#
#  CREATED: 12/31/24
#  BY: Jay A Wilson
#
#  LAST MOD: 12/31/24
#  BY: Jay A Wilson
#  VERSION: 1.00
#
#  MODIFICATION HISTORY:
#      v1.00 = Initial Release
#
#
########

# GLOBAL VARs

DEBUG=0
JDEBUG=0
DSELECT=0
NOTSILENT=1
CLEAN=0
MUEXC=0
LASTARGCHECK=0
FOUNDLOADDEV=0


argcnt=$#
args=("$@")
###########
#
# called by main() to process the arguments
#
###########
do-args(){
  set -- "${args[@]}"
  while [[ $# -gt 0 ]]
  do
      key=`echo "$1" | tr '[:upper:]' '[:lower:]'`
      case $key in
          -afi|--AOSFromip)
              initAOSFromIP="$2"
              if [ "$initAOSFromIP" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
              valid-aosfip
          ;;
          -afu|--AOSFromuid)
              AOSFromUID="$2"
              if [ "$AOSFromUID" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
          ;;
          -afp|--AOSFrompwd)
              AOSFromPWD="$2"
              if [ "$AOSFromPWD" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
          ;;
          -ati|--AOSToip)
              initAOSToIP="$2"
              if [ "$initAOSToIP" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
              valid-aostip
          ;;
          -atu|--AOSTouid)
              AOSToUID="$2"
              if [ "$AOSToUID" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
          ;;
          -atp|--AOSTopwd)
              AOSToPWD="$2"
              if [ "$AOSToPWD" == "" ]; then LASTARGCHECK=1; fi
              shift # past argument
              shift # past value
          ;;
          -h|--help)
              help-info
              exit 0
          ;;
          -x)
              DEBUG=1
              shift
          ;;
          -xj)  # normal DEBUG + DUMP returned JSON returned from curl
              JDEBUG=1
              DEBUG=1
              shift
          ;;
          *)    # unknown option
              POSITIONAL+=("$1") # save it in an array for later
              shift # past argument
          ;;
      esac
  done
  set -- "${POSITIONAL[@]}"
  # verify that if the argument specificed on the command line requires a parm
  #    that the parm was specificed and not forgotten to be entried
  if [ $LASTARGCHECK -eq 1 ]; then
    echo ""; echo " The Last argument on the command is missing it's required parm"; echo " ...exit()"
    exit 1
  fi
  # all the AOS login information is always required
  if [ -z "$AOSFromUID" ] || [ -z "$AOSFromIP" ] || [ -z "$AOSFromPWD" ] ||
     [ -z "$AOSToUID" ] || [ -z "$AOSToIP" ] || [ -z "$AOSToPWD" ]; then
    echo ""; echo " You are missing >=1 AOS parms: -afi, -afu, -afp, -ati, -atu, and/or -atp"; echo " ...exit()"
    exit 1
  fi
  # verify that jq is installed
  if [ -z `which jq` ]; then
    echo " "; echo " The package \"jq\" must be installed to use this script"
    echo " "; echo " Download and installation instructions can be found at:"
    echo " "; echo "     https://https://stedolan.github.io/jq/download/"
    echo " "; echo " ...exit()"
    exit 1
  fi
}
########
#
#  Called by do-args() if --help was specified as the command arg
#
#######
help-info(){
    echo ""
    echo "  This tool allows you to copy all CTs via REST"
    echo "    from a Blueprint to another Blueprint that is managed by"
    echo "    a different Apstra server."
    echo ""
    echo "  Capabilities provided are:"
    echo "      Retrieve Blueprint listing from Juniper AOS,"
    echo "        user selects Blueprint to copy from, and"
    echo "        the Blueprint to copy to."
    echo ""
    echo ""
    echo "  syntax: "
    echo "      eCTcopy -afi|--AOSFromip <hb-ip>     *"
    echo "              -afu|--AOSFromuid <hb-uid>   *"
    echo "              -afp|--AOSFrompwd <hb-pwd>   *"
    echo "              -ati|--AOSToip <hb-ip>     *"
    echo "              -atu|--AOSTouid <hb-uid>   *"
    echo "              -atp|--AOSTopwd <hb-pwd>   *"
    echo "              -h|--help"
    echo ""
    echo "              * = required"
    echo ""
}
#####
#
#  Called to varify IP addresses passed as parms are syntax correct
#
#####
valid-aosfip(){
  rx='([1-9]?[0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
  if [[ $initAOSFromIP =~ ^$rx\.$rx\.$rx\.$rx$ ]]; then
    AOSFromIP=$initAOSFromIP
  else
    echo " IP address for From AOS is not valid"; echo " ...exit()"
    exit 1
  fi
}
valid-aostip(){
  if [[ $initAOSToIP =~ ^$rx\.$rx\.$rx\.$rx$ ]]; then
    AOSToIP=$initAOSToIP
  else
    echo " IP address for To AOS is not valid"; echo " ...exit()"
    exit 1
  fi
}
#####
#
#  Called to output uniform DEBUG messages when -x arg is passed
#
#####
output-debug(){
  local inputstr=$1
  echo "DEBUG: $inputstr" 1>&2
}
#####
#
#  called by main() to clear the files the "curl" statements will use for input
#
#####
clear-json(){
  rm -f -- /tmp/AOSFromtoken.json
  rm -f -- /tmp/AOSTotoken.json
  rm -f -- /tmp/objpolicy.json
  rm -f -- /tmp/VNFroms
  rm -f -- /tmp/VNTos
  rm -f -- /tmp/VNcombined
}
#####
#
#  Build the json needed to ask for a Keystone token for all the other
#  curl calls to the Controller
#
#####
build-tokens(){
  # JSON to request AOS Token
  cat > /tmp/AOSFromtoken.json <<EOF
{
  "username":"${AOSFromUID}",
  "password": "${AOSFromPWD}"
}
EOF
cat > /tmp/AOSTotoken.json <<EOF
{
"username":"${AOSToUID}",
"password": "${AOSToPWD}"
}
EOF
}
#####
#
#  called my main() to get tokens for AOS
#
#####
get-tokens(){
  if [ $NOTSILENT -eq 1 ]; then echo " Getting AOS Authentication Tokens"; fi
  AOSFromtoken=`curl -s -k -H "Content-Type: application/json" --data-binary @/tmp/AOSFromtoken.json -X POST https://$AOSFromIP/api/aaa/login |
  awk '/token/ {print $2};{next}' |
  sed -e 's/",//' -e 's/^"//'`
  AOSTotoken=`curl -s -k -H "Content-Type: application/json" --data-binary @/tmp/AOSTotoken.json -X POST https://$AOSToIP/api/aaa/login |
  awk '/token/ {print $2};{next}' |
  sed -e 's/",//' -e 's/^"//'`
}
#####
#
# called by main() to get a listing of all defined blueprints
#
#####
get-BPlist(){
  #create and array of all the Blueprints defined in the AOS server
  BPFlist=( $(curl -s -H "AuthToken: ${AOSFromtoken}" -H "Content-Type: application/json" -k -X GET https://$AOSFromIP/api/blueprints |
           jq '.items[] | .label, .id' | sed -e 's/ /_/g'  | sed 'N;s/\n/,/' | sed -e 's/"//g') )
  BPFlistelements=${#BPFlist[@]}
  if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPFs) K:(BPFlistelements) $BPFlistelements"; fi
  BPTlist=( $(curl -s -H "AuthToken: ${AOSTotoken}" -H "Content-Type: application/json" -k -X GET https://$AOSToIP/api/blueprints |
          jq '.items[] | .label, .id' | sed -e 's/ /_/g'  | sed 'N;s/\n/,/' | sed -e 's/"//g') )
  BPTlistelements=${#BPTlist[@]}
  if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPTs) K:(BPTlistelements) $BPTlistelements"; fi
}
#####
#
# called by main() to get the details of each blueprint
#
#####
get-BPFdetails(){
  echo " From Blueprints:"
  for((ij=0;ij<$BPFlistelements;ij++))
  do
    BPFname=`echo "${BPFlist[ij]}" | cut -d',' -f1`
    BPFUUID=`echo "${BPFlist[ij]}" | cut -d',' -f2`
    echo $ij" "$BPFname
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPFdetails) K:(BPFname) $BPFname  K:(BPFUUID) $BPFUUID"; fi

    BPFitem=( $(curl -s -H "AuthToken: ${AOSFromtoken}" -H "Content-Type: application/json" -k -X GET https://$AOSFromIP/api/blueprints/${BPFUUID}/experience/web/system-info |
            awk 'BEGIN { RS="," }; { print $0}' | grep -v server |
            grep -A12 hostname | awk 'BEGIN { RS="--"}; {print $0}' |
            grep -e system_id -e role | sed 'N;s/\n/,/' |
            grep -v null | sed 's/",//' | sed 's/"//g') )
    BPFitemelements=${#BPFitem[@]}
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPFdetails) K:(BPFname) $BPFname  K:(BPFlistelements) $BPFlistelements K:(ij) $ij"; fi
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPFdetails) K:(BPFname) $BPFname  K:(BPFitemelements) $BPFitemelements"; fi
    #do-BPdetails
  done
  jfcnt=$(( $ij - 1 ))
  get-BPfromNumber
  fromBPname=`echo "${BPFlist[fromsponse]}" | cut -d',' -f1`
  fromBPUUID=`echo "${BPFlist[fromsponse]}" | cut -d',' -f2`
}
get-BPTdetails(){
  echo " To Blueprints:"
  for((ij=0;ij<$BPTlistelements;ij++))
  do
    BPTname=`echo "${BPTlist[ij]}" | cut -d',' -f1`
    BPTUUID=`echo "${BPTlist[ij]}" | cut -d',' -f2`
    echo $ij" "$BPTname
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPTdetails) K:(BPTname) $BPTname  K:(BPTUUID) $BPTUUID"; fi

    BPTitem=( $(curl -s -H "AuthToken: ${AOSTotoken}" -H "Content-Type: application/json" -k -X GET https://$AOSToIP/api/blueprints/${BPTUUID}/experience/web/system-info |
            awk 'BEGIN { RS="," }; { print $0}' | grep -v server |
            grep -A12 hostname | awk 'BEGIN { RS="--"}; {print $0}' |
            grep -e system_id -e role | sed 'N;s/\n/,/' |
            grep -v null | sed 's/",//' | sed 's/"//g') )
    BPTitemelements=${#BPTitem[@]}
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPTdetails) K:(BPTname) $BPTname  K:(BPTlistelements) $BPTlistelements K:(ij) $ij"; fi
    if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPTdetails) K:(BPTname) $BPTname  K:(BPTitemelements) $BPTitemelements"; fi
    #do-BPdetails
  done
  jtcnt=$(( $ij - 1 ))
  get-BPtoNumber
  toBPname=`echo "${BPTlist[tosponse]}" | cut -d',' -f1`
  toBPUUID=`echo "${BPTlist[tosponse]}" | cut -d',' -f2`
}
#####
#
# called by get-BPdetails() to get user input as to the FROM BP
#
#####
get-BPfromNumber(){
  loop2=0
  echo ""
  echo " Input \"FROM\" Number "
  while [ $loop2 -eq 0 ]
  do
     read fromsponse
     case $fromsponse in
       [0-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][1-9])
          if [ "$fromsponse" -ge "0" ] && [ "$fromsponse" -le "$jfcnt" ]; then
             loop2=1
          else
             echo " Number entered is not a valid selection...try again"
          fi
          ;;
       *) echo " Invalid character...try again"
          ;;
     esac
     if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPfromNumber) K:(fromsponse) $fromsponse"; fi
  done
}
#####
#
# called by get-BPdetails() to get user input as to the TO BP
#
#####
get-BPtoNumber(){
  loop2=0
  echo ""
  echo " Input \"TO\" Number "
  while [ $loop2 -eq 0 ]
  do
     read tosponse
     case $tosponse in
       [0-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][1-9])
          if [ "$tosponse" -ge "0" ] && [ "$tosponse" -le "$jtcnt" ]; then
             loop2=1
          else
             echo " Number entered is not a valid selection...try again"
          fi
          ;;
       *) echo " Invalid character...try again"
          ;;
     esac
     if [ $DEBUG -eq 1 ]; then output-debug "R:(get-BPtoNumber) K:(tosponse) $tosponse"; fi
  done
}
#####
#
# called by main() to get the VN UUIDs from the FROM BP
#
#####
get-VNFromIDs(){
  fromBPname=`echo "${BPFlist[fromsponse]}" | cut -d',' -f1`
  fromBPUUID=`echo "${BPFlist[fromsponse]}" | cut -d',' -f2`
  if [ $DEBUG -eq 1 ]; then output-debug "R:(get-VNFromIDs) K:(fromBPname) $fromBPname  K:(fromBPUUID) $fromBPUUID"; fi
  rm /tmp/VNFroms 2>/dev/null
  # get the subpolicy that points to a VN UUID
  for svkmh in `curl -s -H "AuthToken: ${AOSFromtoken}" -H "Content-Type: application/json" -k -X GET https://$AOSFromIP/api/blueprints/${fromBPUUID}/obj-policy-export |
  jq -r '[.policies[] | select(.policy_type_name != "pipeline" and .policy_type_name != "batch")| .attributes.vn_node_id] | unique | .[]' | sed 's/\"//g'`
  do
    curl -s -H "AuthToken: ${AOSFromtoken}" -H "Content-Type: application/json" -k -X GET https://$AOSFromIP/api/blueprints/${fromBPUUID}/virtual-networks/${svkmh} |
    jq '"\(.id),\(.vn_id)"' >> /tmp/VNFroms
  done
  sed -i '' -e 's/"//g' /tmp/VNFroms
}
#####
#
# called by main() to get the VN UUIDs and VN IDs from the TO BP
#
#####
get-VNToIDs(){
  toBPname=`echo "${BPTlist[tosponse]}" | cut -d',' -f1`
  toBPUUID=`echo "${BPTlist[tosponse]}" | cut -d',' -f2`
  if [ $DEBUG -eq 1 ]; then output-debug "R:(get-VNToIDs) K:(toBPname) $toBPname  K:(toBPUUID) $toBPUUID"; fi
  # Retrieve the VN UUID listing and each associated VN_ID
  curl -s -H "AuthToken: ${AOSTotoken}" -H "Content-Type: application/json" -k -X GET https://$AOSToIP/api/blueprints/${toBPUUID}/virtual-networks |
  jq '.virtual_networks[] | "\(.id),\(.vn_id)"' |   sed -e 's/"//g' > /tmp/VNTos
}
#####
#
# called by main() to combine the VN UUIDs in the FROM BP with the TO BP
#
#####
do-VNcombine(){
  awk -F, '
  NR == FNR {  # Process /tmp/VNFroms first
    # Store the values in an array
    # use the vn_id as the index for each array element and store the id in it
    fromvninfo[$2] = $1;
    next;
  }

  # Process /tmp/VNTos now
  {
    # Extract the vn_id from /tmp/VNTos
    svalue = $2;
    # If the value exists in the fromvninfo array, print it
    if (svalue in fromvninfo) {
      print $0 "," fromvninfo[svalue];
    }
  }
' /tmp/VNTos /tmp/VNFroms > /tmp/VNcombined
}
#####
#
# called by main() to retrieve CTs from the FROM BP
#
#####
get-CTFrom(){
  echo ""
  echo "Retrieving CTs from the FROM BP"
  fromBPname=`echo "${BPFlist[fromsponse]}" | cut -d',' -f1`
  fromBPUUID=`echo "${BPFlist[fromsponse]}" | cut -d',' -f2`
  if [ $DEBUG -eq 1 ]; then output-debug "R:(get-CTFrom) K:(fromBPname) $fromBPname  K:(fromBPUUID) $fromBPUUID"; fi
  #toBPname=`echo "${BPlist[tosponse]}" | cut -d',' -f2`
  #toBPUUID=`echo "${BPlist[tosponse]}" | cut -d',' -f1`
  #if [ $DEBUG -eq 1 ]; then output-debug "R:(get-CTFrom) K:(toBPname) $toBPname  K:(toBPUUID) $toBPUUID"; fi
  objpolicy=`curl -s -H "AuthToken: ${AOSFromtoken}" -H "Content-Type: application/json" -k -X GET https://$AOSFromIP/api/blueprints/${fromBPUUID}/obj-policy-export`
  echo $objpolicy | jq '.' > /tmp/objpolicy.json
  do-obj-mod
  #curl -s -k -H "AuthToken: ${AOStoken}"  -H "Content-Type: application/json" --data-binary @/tmp/objpolicy.json -X PUT https://$AOSIP/api/blueprints/${toBPUUID}/obj-policy-import
}
#####
#
# called by get-CTFrom() to update the TO BPs CT Policies with the new UUIDs
#
#####
do-obj-mod(){
  # modified the saved CT Policies file with the new UUIDs
  for combinedlist in `cat /tmp/VNcombined`; do
    vnuuidold=`echo "${combinedlist}" | cut -d',' -f1`
    jvnid=`echo "${combinedlist}" | cut -d',' -f2`
    vnuuidnew=`echo "${combinedlist}" | cut -d',' -f3`
    if [ $DEBUG -eq 1 ]; then output-debug "R:(do-obj-mod) K:(vnid) $jvnid  K:(vnuuidold) $vnuuidold  K:(vnuuidnew) $vnuuidnew"; fi
    sed -i '' "s/$vnuuidold/$vnuuidnew/g" /tmp/objpolicy.json
  done
}
#####
#
# called by main() to push the modified CTs into the TO BP
#
#####
do-CTTo(){
  echo ""
  echo "Installing CTs in the TO BP"
  toBPname=`echo "${BPTlist[tosponse]}" | cut -d',' -f1`
  toBPUUID=`echo "${BPTlist[tosponse]}" | cut -d',' -f2`
  if [ $DEBUG -eq 1 ]; then output-debug "R:(do-CTTo) K:(toBPname) $toBPname  K:(toBPUUID) $toBPUUID"; fi
  curl -s -k -H "AuthToken: ${AOSTotoken}"  -H "Content-Type: application/json" --data-binary @/tmp/objpolicy.json -X PUT https://$AOSToIP/api/blueprints/${toBPUUID}/obj-policy-import
}
#####
#
# main()
#
#####
do-args
clear-json
build-tokens
get-tokens
get-BPlist
get-BPFdetails
get-BPTdetails
get-VNFromIDs
get-VNToIDs
do-VNcombine
get-CTFrom
do-CTTo
if [ $DEBUG -eq 0 ]; then clear-json; fi
